import Header from '@/components/landing/Header';
import Hero from '@/components/landing/Hero';
import About from '@/components/landing/About';
import ServicesSection from '@/components/landing/ServicesSection';
import MissionValues from '@/components/landing/MissionValues';
import Timeline from '@/components/landing/Timeline';
import CompanyData from '@/components/landing/CompanyData';
import ContactSection from '@/components/landing/ContactSection';
import Footer from '@/components/landing/Footer';
import { getCompanyLandingData } from '@/lib/landing/company-landing-data';

/**
 * Custom Domain Landing Page (Meta / Facebook Verified Standard)
 *
 * Serves the full institutional landing page for any custom domain registered
 * in verified_domains. Traffic arrives here via middleware rewrite.
 * Uses multi-provider CNPJ fetching (ReceitaWS/BrasilAPI/CNPJ.WS) for 100% address accuracy.
 */

interface Props {
    params: Promise<{ domain: string }>;
}

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'https://score-scanner-7q2s.vercel.app';

export default async function CustomDomainPage({ params }: Props) {
    const { domain } = await params;
    const company = await getCompanyLandingData(domain);

    if (!company) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-slate-900 text-white">
                <div className="text-center p-8 bg-slate-800 border border-slate-700 shadow-2xl rounded-2xl max-w-md">
                    <span className="text-4xl mb-4 block">🌐</span>
                    <h1 className="text-2xl font-bold mb-2">Domínio em Configuração</h1>
                    <p className="text-slate-400 text-sm">
                        Este domínio aponta para a infraestrutura, mas a empresa vinculada está sendo ativada no painel.
                    </p>
                </div>
            </div>
        );
    }

    const {
        cleanDisplayName,
        razaoSocial,
        cnpj,
        formattedCNPJ,
        dataInicioAtividade,
        foundedYear,
        porte,
        naturezaJuridica,
        cnaeCodigo,
        cnaeDescricao,
        cnaesSecundarios,
        fullAddress,
        municipio,
        uf,
        cep,
        telefone,
        contactEmail,
        description,
        verificationToken,
        pixelId,
        canonicalUrl,
    } = company;

    // OG Image URL (generated by /api/og edge route)
    const ogImageParams = new URLSearchParams({
        name: cleanDisplayName,
        cnpj: formattedCNPJ,
        city: municipio || '',
    });
    const ogImageUrl = `${BASE_URL}/api/og?${ogImageParams.toString()}`;

    return (
        <html lang="pt-BR" className="scroll-smooth">
            <head>
                <meta charSet="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />

                {/* === Facebook Domain Verification === */}
                {verificationToken && (
                    <meta name="facebook-domain-verification" content={verificationToken} />
                )}

                {/* === SEO === */}
                <title>{cleanDisplayName} — Portal Institucional Oficial</title>
                <meta name="description" content={description} />
                <link rel="canonical" href={canonicalUrl} />
                <meta name="robots" content="index, follow" />

                {/* === Open Graph (Facebook / WhatsApp / LinkedIn) === */}
                <meta property="og:type" content="website" />
                <meta property="og:url" content={canonicalUrl} />
                <meta property="og:title" content={`${cleanDisplayName} — Informações Institucionais`} />
                <meta property="og:description" content={description} />
                <meta property="og:image" content={ogImageUrl} />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="630" />
                <meta property="og:image:alt" content={`Identidade de ${cleanDisplayName}`} />
                <meta property="og:locale" content="pt_BR" />
                <meta property="og:site_name" content={cleanDisplayName} />

                {/* === Twitter Card === */}
                <meta name="twitter:card" content="summary_large_image" />
                <meta name="twitter:title" content={`${cleanDisplayName} — Portal Oficial`} />
                <meta name="twitter:description" content={description} />
                <meta name="twitter:image" content={ogImageUrl} />

                {/* === Facebook Pixel === */}
                {pixelId && (
                    <>
                        <script dangerouslySetInnerHTML={{
                            __html: `
                                !function(f,b,e,v,n,t,s)
                                {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                                n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                                if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                                n.queue=[];t=b.createElement(e);t.async=!0;
                                t.src=v;s=b.getElementsByTagName(e)[0];
                                s.parentNode.insertBefore(t,s)}(window, document,'script',
                                'https://connect.facebook.net/en_US/fbevents.js');
                                fbq('init', '${pixelId}');
                                fbq('track', 'PageView');
                            `
                        }} />
                        <noscript>
                            <img height="1" width="1" style={{ display: 'none' }}
                                src={`https://www.facebook.com/tr?id=${pixelId}&ev=PageView&noscript=1`}
                                alt=""
                            />
                        </noscript>
                    </>
                )}
            </head>

            <body className="antialiased bg-slate-50 text-slate-900 font-sans">
                {/* 1. Header with direct navigation */}
                <Header companyName={cleanDisplayName} />

                <main>
                    {/* 2. Hero — trust-centered positioning */}
                    <Hero
                        companyName={cleanDisplayName}
                        razaoSocial={razaoSocial}
                        description={description}
                        cnpj={formattedCNPJ}
                        municipio={municipio}
                        uf={uf}
                        foundedYear={foundedYear}
                    />

                    {/* 3. About — corporate identity and compliance */}
                    <About
                        companyName={cleanDisplayName}
                        razaoSocial={razaoSocial}
                        foundedDate={dataInicioAtividade || ''}
                        porte={porte}
                        naturezaJuridica={naturezaJuridica}
                        municipio={municipio}
                        uf={uf}
                        cnpj={cnpj}
                    />

                    {/* 4. Services / Economic Activity — tailored by CNAE */}
                    <ServicesSection
                        companyName={cleanDisplayName}
                        cnaeCodigo={cnaeCodigo}
                        cnaeDescricao={cnaeDescricao}
                        cnaesSecundarios={cnaesSecundarios}
                    />

                    {/* 5. Mission / Vision / Ethics */}
                    <MissionValues companyName={cleanDisplayName} />

                    {/* 6. Timeline — historical evolution */}
                    <Timeline
                        foundedDate={dataInicioAtividade || ''}
                        companyName={cleanDisplayName}
                    />

                    {/* 7. Company Cadastral Data — 100% accurate address */}
                    <CompanyData company={company} />

                    {/* 8. Contact & Interactive Message Form */}
                    <ContactSection
                        companyName={cleanDisplayName}
                        address={fullAddress}
                        municipio={municipio}
                        uf={uf}
                        cep={cep}
                        telefone={telefone}
                        email={contactEmail}
                    />
                </main>

                {/* 9. Footer with accessible terms & privacy links */}
                <Footer
                    companyName={cleanDisplayName}
                    razaoSocial={razaoSocial}
                    cnpj={formattedCNPJ}
                    address={fullAddress}
                />
            </body>
        </html>
    );
}

// Dynamic metadata
export async function generateMetadata({ params }: Props) {
    const { domain } = await params;
    const company = await getCompanyLandingData(domain);

    if (!company) {
        return { title: 'Domínio em Configuração' };
    }

    const { cleanDisplayName, formattedCNPJ, municipio, description, canonicalUrl } = company;
    const ogImageUrl = `${BASE_URL}/api/og?name=${encodeURIComponent(cleanDisplayName)}&cnpj=${formattedCNPJ || ''}`;

    return {
        title: `${cleanDisplayName} — Portal Institucional Oficial`,
        description: description || `Informações institucionais e canais de contato de ${cleanDisplayName}.`,
        openGraph: {
            type: 'website',
            url: canonicalUrl,
            title: `${cleanDisplayName} — Portal Institucional`,
            description: description || `Informações institucionais e canais de contato de ${cleanDisplayName}.`,
            images: [{ url: ogImageUrl, width: 1200, height: 630, alt: cleanDisplayName }],
            locale: 'pt_BR',
        },
        twitter: {
            card: 'summary_large_image',
            title: `${cleanDisplayName} — Portal Oficial`,
            description: description,
            images: [ogImageUrl],
        },
    };
}
